mysite/myapp/urls.py
from django.urls import path
from .views import dashbord, edit, delete,index
app_name = "myapp"
urlpatterns = [
    path('',index, name="index"),
    path('edit/<int:id>', edit, name="edit"),
    path('delete/<int:id>', delete, name="delete"),
    path('dashbord/',dashbord.as_view(),name='dashbord')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('user/',include('user.urls')),
    path('', include('allauth.urls')),
]

mysite/user/urls.py
from django.urls import path,include
from .views import register,LoginView,Logout


app_name='user'
urlpatterns = [
    path('register/',register,name='register'),
    path('login/',LoginView,name='login'),
    path('logout/',Logout,name='logout'),
]

mysite/myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Expense(models.Model):
    def __str__(self):
        return self.name
    Username = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    amount = models.FloatField()
    category = models.CharField(max_length=50, choices=[
                                ("Housing", "Housing"), ("Transportation", "Transportation"), ("Personal Care", "Personal Care"), ("Taxes", "Taxes"), ("Food", "Food "), ("Healthcare", "Healthcare"), ("Utilities", "Utilities"), ("Fun", "Fun"), ("Gifts", "Gifts"), ("Home Supplies", "Home Supplies"), ("Clothes", "Clothes"), ("Other","Other")])
    date = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('myapp:index', kwargs={})

mysite/user/models.py
from django.db import models

# Create your models here.

mysite/myapp/forms.py
from django.forms import ModelForm
from .models import Expense
class ExpanseFrom(ModelForm):
    class Meta:
        model=Expense
        fields=('name','amount','category')

mysite/myapp/views.py
from django.shortcuts import render, redirect
from .forms import ExpanseFrom
from .models import Expense
from django.views.generic.edit import CreateView
from django.db.models import Sum
import datetime
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    return render(request, 'myapp/index.html')


@method_decorator(login_required, name='dispatch')
class dashbord(CreateView):
    model = Expense
    fields = ['name', 'amount', 'category']
    template_name = 'myapp/dashbord.html'

    def form_valid(self, form):
        form.instance.Username = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        print(self.request.user)
        last_three_month = datetime.date.today() - datetime.timedelta(days=90)
        expanses = Expense.objects.filter(
            date__gt=last_three_month, Username=self.request.user).order_by('-date')
        total_expenses = expanses.aggregate(Sum('amount'))
        last_year = datetime.date.today() - datetime.timedelta(days=365)
        data = Expense.objects.filter(
            date__gt=last_year, Username=self.request.user)
        yearly_sum = data.aggregate(Sum('amount'))
        last_month = datetime.date.today() - datetime.timedelta(days=30)
        data = Expense.objects.filter(
            date__gt=last_month, Username=self.request.user)
        monthly_sum = data.aggregate(Sum('amount'))
        last_week = datetime.date.today() - datetime.timedelta(days=7)
        data = Expense.objects.filter(
            date__gt=last_week, Username=self.request.user)
        weekly_sum = data.aggregate(Sum('amount'))
        daily_sum = Expense.objects.filter(date__gt=last_month, Username=self.request.user).values(
            'date').order_by('-date').annotate(sum=Sum('amount'))
        categorical_sum = Expense.objects.filter(date__gt=last_month, Username=self.request.user).values(
            'category').order_by('category').annotate(sum=Sum('amount'))
        context = super(dashbord, self).get_context_data(**kwargs)
        context.update({'expenses': expanses,
                        'total_expenses': total_expenses, 'yearly_sum': yearly_sum, 'monthly_sum': monthly_sum, 'weekly_sum': weekly_sum, 'daily_sum': daily_sum, 'categorical_sum': categorical_sum})
        return context
    # return render(request,'myapp/index.html',{'expenses':expanses,"total_expenses":total_expenses,'yearly_sum':yearly_sum,'monthly_sum':monthly_sum,'weekly_sum':weekly_sum,'daily_sum':daily_sum,'categorical_sum':categorical_sum})

# def index(request):
#     expense_form=ExpanseFrom()
#     if request.method == "POST":
#         expanse=ExpanseFrom(request.POST)
#         if expanse.is_valid():
#             expanse.save()
    # expanses=Expense.objects.all()
    # total_expenses=expanses.aggregate(Sum('amount'))
    # last_year=datetime.date.today() - datetime.timedelta(days=365)
    # data=Expense.objects.filter(date__gt=last_year)
    # yearly_sum=data.aggregate(Sum('amount'))
    # last_month=datetime.date.today() - datetime.timedelta(days=30)
    # data=Expense.objects.filter(date__gt=last_month)
    # monthly_sum=data.aggregate(Sum('amount'))
    # last_week=datetime.date.today() - datetime.timedelta(days=7)
    # data=Expense.objects.filter(date__gt=last_week)
    # weekly_sum=data.aggregate(Sum('amount'))
    # daily_sum=Expense.objects.filter().values('date').order_by('date').annotate(sum=Sum('amount'))
    # categorical_sum=Expense.objects.filter().values('category').order_by('category').annotate(sum=Sum('amount'))
    # return render(request,'myapp/index.html',{'expense':expense_form,'expenses':expanses,"total_expenses":total_expenses,'yearly_sum':yearly_sum,'monthly_sum':monthly_sum,'weekly_sum':weekly_sum,'daily_sum':daily_sum,'categorical_sum':categorical_sum})


def edit(request, id):
    expense = Expense.objects.get(pk=id)
    expense_form = ExpanseFrom(instance=expense)
    # print(request.user,expense.Username)
    if request.user == expense.Username:
        if request.method == "POST":
            expense = Expense.objects.get(pk=id)
            form = ExpanseFrom(request.POST, instance=expense)
            if form.is_valid():
                expense.save()
                return redirect("myapp:dashbord")
        return render(request, 'myapp/edit.html', {'expense': expense_form})
    return redirect('user:dashbord')


def delete(request, id):
    if request.user == expense.Username:
        if request.method == "POST" and 'delete' in request.POST:
            expense = Expense.objects.get(pk=id)
            expense.delete()
        return redirect('myapp:dashbord')
    return redirect('user:dashbord')

mysite/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from .form import Registration
from django.contrib.auth.forms import AuthenticationForm
def register(request):
    print(request.user)
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=Registration(request.POST)
            if form.is_valid():
                form.save()
                return redirect('user:login')
        else:
            form=Registration()
        return render(request,'user/Signup.html',{'form':form})
    else:
        return redirect("myapp:index")



def LoginView(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
                form = AuthenticationForm(request, data=request.POST)
                if form.is_valid():
                    username = form.cleaned_data.get('username')
                    password = form.cleaned_data.get('password')
                    user = authenticate(request, username=username, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect("myapp:dashbord")
        else:
            form = AuthenticationForm()

        return render(request, 'user/login.html', {'form': form})
    return redirect('myapp:index')
def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('user:login')
    else:
        return redirect('user:login')

mysite/myapp/templates/myapp/dashbord.html
{% extends 'myapp/base.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<section class="container-fluid  border-red-200 flex flex-col items-center justify-center">
    <div class="  w-[90%] font-bold text-['poppins'] text-4xl text-[#003E59]">Add Expense</div>
    <form method="post" class="border container  m-10 rounded-[20px] text-['poppins']">
        {% csrf_token %}

        <div class="container-fluid w-[100%] py-10 flex">
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Expense Name</label>
                </div>
                    <input type="{{ form.name.field.widget.input_type }}" placeholder="Ex-IPhone"  required class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]" name="{{ form.name.name}}" id="{{ form.name.auto_id}}">
            </div>
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Amount</label>
                </div>
                    <input type="{{ form.amount.field.widget.input_type }}"
                        class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]" name="{{ form.amount.name}}" min="0" oninput="validity.valid||(value='');"  placeholder="Ex-2000₹"
                        id="{{ form.amount.auto_id}}">
            </div>
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Category</label>
                </div>
                <select required name="{{ form.category.name}}" id="{{ form.category.auto_id}}"  class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]">
                {% for id, value in form.category.field.choices %}
                    {% if not id %}
                    <option value="{{ id }}" hidden selected>Select Category</option>
                    {% else %}
                    <option value="{{ id }}">{{value}}</option>
                    {% endif %}
                {% endfor %}
                </select>
               
            </div>
            <div class="mx-10 my-9">
                <button class="bg-[#00ED64] border rounded-full p-3 text-lg  w-[130px] border-[#003E59]">Add</button>
            </div>
        </div>
    </form>
</section>
<section class="mt-10 container-fluid  border-red-200 flex flex-col items-center justify-center">
    <div class="font-bold w-[90%] text-['poppins'] text-4xl text-[#003E59]"> Expenses</div>
    <table class=" mt-10  rounded-[20px] container w-[90%] text-center" rules="">
        <tr class="">
            <th class="border  text-xl p-3 font-medium text-[#00684A]"><span>Name</span></th>
            <th class="border  text-xl p-3 font-medium text-[#00684A]"><span>Amount</span></th>
            <th class="border text-xl p-3 font-medium text-[#00684A]"><span>Date</span></th>
            <th class="border text-xl p-3 font-medium text-[#00684A]"><span>Category</span></th>
            <th class="border text-xl p-3 font-medium text-[#00684A]"><span>Edit</span></th>
            <th class="border text-xl p-3 font-medium text-[#00684A]"><span>Delete</span></th>
        </tr>
        {% for i in expenses %}
        <tr>
            <td class="border text-lg p-2  text-[#003E59]"><span class="font-medium">{{i.name}}</span></td>
            <td class="border text-lg p-2  text-[#003E59]"><span class="font-medium">₹{{i.amount|intcomma}}</span>
            </td>
            <td class="border text-lg p-2  text-[#003E59]"><span class="font-medium">{{i.date}}</span></td>
            <td class="border text-lg p-2  text-[#003E59]"><span class="font-medium">{{i.category}}</span></td>
            <td class="border flex py-3 justify-center items-center ">
                <span class="font-medium">
                    <a href="{% url 'myapp:edit' i.id %}">
                        <img src="{% static 'myapp/images/edit.png' %}" width="20" height="20" >
                    </a></span>
            </td>
            <td class="border">
                <form method="post" action="{% url 'myapp:delete' i.id %}">
                    {% csrf_token %}
                    <span class="font-bold">
                        <button type="submit" name="delete" class="py-2">
                            <svg height="23" viewBox="0 0 48 48" width="23" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M12 38c0 2.21 1.79 4 4 4h16c2.21 0 4-1.79 4-4V14H12v24zM38 8h-7l-2-2H19l-2 2h-7v4h28V8z" />
                                <path d="M0 0h48v48H0z" fill="none" />
                            </svg>
                        </button>
                    </span>
                </form>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="5" class="border text-xl p-3 font-medium text-[#003E59] ">Total</td>
            <td class="border text-xl p-3 font-medium text-[#003E59]">₹{{total_expenses.amount__sum|intcomma}}</td>
        </tr>
    </table>
</section>
<section class="mt-10 container-fluid flex flex-col items-center justify-center">

    <div class="container w-[90%] flex justify-between gap-4">
        <div class="border  rounded-lg p-4 w-1/3">
            <h1 class=" font-bold w-[90%] text-['poppins'] text-2xl p-2  text-[#003E59]">Last 365 Days</h1>
            <h1 class=" text-green-500 text-xl font-bold">
                ₹{{yearly_sum.amount__sum|intcomma}}
            </h1>
        </div>
        <div class="border  rounded-lg p-4 w-1/3">
            <h1 class=" font-bold w-[90%] text-['poppins'] text-2xl p-2  text-[#003E59]">Last 30 Days</h1>
            <h1 class=" text-green-500 text-xl font-bold">
                ₹{{monthly_sum.amount__sum|intcomma}}
            </h1>
        </div>
        <div class="border  rounded-lg p-4 w-1/3">
            <h1 class=" font-bold w-[90%] text-['poppins'] text-2xl p-2  text-[#003E59]">Last 7 Days</h1>
            <h1 class=" text-green-500 text-xl font-bold">
                ₹{{weekly_sum.amount__sum|intcomma}}
            </h1>
        </div>
    </div>
</section>
<section class=" mt-10 container-fluid  border-red-200 flex flex-col items-center justify-center">
    <div class="conatiner w-[90%] flex gap-4">
        <div class="w-1/2 border rounded-[10px]">
            <div class="flex flex-wrap space-x-40 font-bold text-2xl p-4 text-[#003E59] ">
                <span>Past 30 Days Sum Expanse</span>
            </div>
            <hr>
            <div id="30-day-table">
                {% for i in daily_sum %}
                <div class="flex flex-wrap p-4 text-xl text-[#00684A]">
                    <span>
                        {{i.date}}
                    </span>
                </div>
                <div class="flex flex-wrap p-4">
                    <span class="text-green-500">₹{{i.sum|intcomma}}</span>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="w-1/2 border rounded-[10px]">
            <div class="flex flex-wrap space-x-40 font-bold text-2xl p-4 text-[#003E59] ">
                <span>Past 30 Days Categorical Expenses</span>
            </div>
            <hr>
            <div id="cate-sum-table" class="m-4">
                {% for i in categorical_sum %}
                <div class="flex flex-wrap p-4 text-xl text-[#00684A]">
                    <span>
                        {{i.category}}
                    </span>
                </div>
                <div class="flex flex-wrap p-4">
                    <span class="text-green-500">₹{{i.sum|intcomma}}</span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<section class=" mt-10 container-fluid  border-red-200 flex flex-col items-center justify-center">
    <div class="flex container w-[90%] items-center justify-between gap-4">
        <div class="w-1/2 border rounded-[10px] ml-10">
            <h1 class="text-2xl text-[#00684A] p-4">Last 30 days Expanse spread Across Categories</h1>
            <canvas id="myChart" class="m-10"></canvas>
        </div>
        <div class="w-1/2 border rounded-[10px] ml-10">
            <h1 class="text-2xl text-[#00684A] p-4">Last 30 days Daily Expanse Sum</h1>
            <canvas id="myChart_Daily" class="m-10"></canvas>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.min.js"></script>
<script>
    const cateSumDiv = document.getElementById('cate-sum-table').getElementsByTagName('div')
    console.log(cateSumDiv)
    const cats = []
    const cat_sums = []
    for (i = 0; i < cateSumDiv.length; i++) {
        if (i % 2 == 0) {
            cats.push(cateSumDiv[i].innerText)
        }
        else {
            var price = cateSumDiv[i].innerText.replace('₹', '')
            cat_sums.push(parseFloat(price.replace(',', '')))
        }
    }
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: cats,
            datasets: [{
                label: 'Expense Across Category',
                data: cat_sums,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    const DailysumDiv = document.getElementById('30-day-table').getElementsByTagName('div')

    const Dates = []
    const Sums = []
    for (i = 0; i < DailysumDiv.length; i++) {
        if (i % 2 == 0) {
            Dates.push(DailysumDiv[i].innerText)
        }
        else {
            var price = DailysumDiv[i].innerText.replace('₹', '')
            Sums.push(parseFloat(price.replace(',', '')))
        }
    }
    var ctx1 = document.getElementById('myChart_Daily').getContext('2d');
    var myChart = new Chart(ctx1, {
        type: 'line',
        data: {
            labels: Dates.reverse(),
            datasets: [{
                label: 'Sum of Daily Expanse',
                data: Sums.reverse(),
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>
{% endblock %}

mysite/myapp/templates/myapp/edit.html
{% extends 'myapp/base.html' %}
{% block body %}
<section class="container-fluid  border-red-200 flex flex-col items-center justify-center">
    <div class="  w-[90%] font-bold text-['poppins'] text-4xl text-[#003E59]">Add Expense</div>
    <form method="post" class="border container  m-10 rounded-[20px] text-['poppins']">
        {% csrf_token %}

        <div class="container-fluid w-[100%] py-10 flex">
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Expense Name</label>
                </div>
                <input type="{{ expense.name.field.widget.input_type }}" placeholder="Ex-IPhone" required
                    class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]"
                    name="{{ expense.name.name}}" value="{{expense.name.value}}"  id="{{ form.name.auto_id}}">
            </div>
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Amount</label>
                </div>
                <input type="{{ expense.amount.field.widget.input_type }}"
                    class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]"
                    name="{{ expense.amount.name}}" value="{{expense.amount.value}}" min="0" oninput="validity.valid||(value='');" placeholder="Ex-2000₹"
                    id="{{ expense.amount.auto_id}}">
            </div>
            <div class="mx-10">
                <div class="mb-2 text-xl ml-3 font-medium text-[#00684A]">
                    <label>Category</label>
                </div>
                <select required name="{{ expense.category.name}}" id="{{ expense.category.auto_id}}"
                    class="border rounded-full p-3 text-lg text-[#00684A] w-[300px] hover:border-[#003E59]">
                    {% for id, value in expense.category.field.choices %}
                    {% if id == expense.category.value %}
                    <option value="{{ id }}" selected>{{value}}</option>
                    {% else %}
                    <option value="{{ id }}">{{value}}</option>
                    {% endif %}
                    {% endfor %}
                </select>

            </div>
            <div class="mx-10 my-9">
                <button class="bg-[#00ED64] border rounded-full p-3 text-lg  w-[130px] border-[#003E59]">Add</button>
            </div>
        </div>
    </form>
</section>

{% endblock %}

mysite/user/templates/user/login.html
{% extends 'myapp/base.html' %}
{% load socialaccount %}
{% load static %}
{% block body %}
<body >
    <center>
        <section class="flex justify-center items-center border-green-900 p-5 font-['poppins']">
            <div class="border border-[#D4D4D4] flex flex-row justify-center items-center  max-[768px]:flex-col rounded-[40px] overflow-x-hidden p-6  md:space-y-0">
                
                <div class=" border-blue-700 w-[50%] max-[768px]:w-[60%]">
                    <img src="{% static 'myapp/images/registerimg.png' %}" class="w-[100%]  border-blue-700" alt="Registration Image">
                </div>
                <div class=" border-black w-full md:w-[50%] text-center md:text-left  ">
                    <div class=" border-orange-700 mb-6 text-center text-5xl max-[768px]:text-4xl  font-bold text-[#00ED64]">
                        Login
                    </div>
                    <form method="post" class="flex flex-col p-3 space-y-4 place-content-center w-full font-['poppins']">
                        {% csrf_token %}
                        <!-- username -->
                        <input type="{{ form.username.field.widget.input_type }}" name="{{ form.username.name }}" id="{{form.username.auto_id}}" class="border border-[#D4D4D4] text-lg  p-3 focus:outline-[#00ED64] text-[#00684A] rounded-full" required placeholder="Username">
                        <!-- password -->
                        <input type="{{ form.password.field.widget.input_type }}" name="{{ form.password.name }}" id="{{ form.password.auto_id }}" class="border border-[#D4D4D4] text-lg  p-3 focus:outline-[#00ED64] text-[#00684A]  rounded-full" required placeholder="Password">

                        
                        <!-- submit button -->
                        <input type="submit" class="text-xl p-4 w-[100%]   rounded-full bg-[#003E59] text-white cursor-pointer hover:bg-[#00ED64]">
                         <span class="text-center p-2 text-gray-700">Don't have an account ?  <a href="{% url 'user:register' %}" class="text-[#00ED64] hover:text-[#001E2B] hover:underline">Sign Up</a></span>
                        <a  href="{% provider_login_url 'google'%}?next=/"
                            class="text-xl p-4 w-[100%] flex items-center justify-center rounded-full bg-[#00ED64] text-white cursor-pointer hover:bg-[#003E59]">
                            Sign Up With&#160;
                            <svg xmlns="http://www.w3.org/2000/svg" fill="#fff" viewBox="0 0 50 50" width="35px">
                                <path
                                    d="M 26 2 C 13.308594 2 3 12.308594 3 25 C 3 37.691406 13.308594 48 26 48 C 35.917969 48 41.972656 43.4375 45.125 37.78125 C 48.277344 32.125 48.675781 25.480469 47.71875 20.9375 L 47.53125 20.15625 L 46.75 20.15625 L 26 20.125 L 25 20.125 L 25 30.53125 L 36.4375 30.53125 C 34.710938 34.53125 31.195313 37.28125 26 37.28125 C 19.210938 37.28125 13.71875 31.789063 13.71875 25 C 13.71875 18.210938 19.210938 12.71875 26 12.71875 C 29.050781 12.71875 31.820313 13.847656 33.96875 15.6875 L 34.6875 16.28125 L 41.53125 9.4375 L 42.25 8.6875 L 41.5 8 C 37.414063 4.277344 31.960938 2 26 2 Z M 26 4 C 31.074219 4 35.652344 5.855469 39.28125 8.84375 L 34.46875 13.65625 C 32.089844 11.878906 29.199219 10.71875 26 10.71875 C 18.128906 10.71875 11.71875 17.128906 11.71875 25 C 11.71875 32.871094 18.128906 39.28125 26 39.28125 C 32.550781 39.28125 37.261719 35.265625 38.9375 29.8125 L 39.34375 28.53125 L 27 28.53125 L 27 22.125 L 45.84375 22.15625 C 46.507813 26.191406 46.066406 31.984375 43.375 36.8125 C 40.515625 41.9375 35.320313 46 26 46 C 14.386719 46 5 36.609375 5 25 C 5 13.390625 14.386719 4 26 4 Z" />
                            </svg>
                        </a>
                    </form>
                            {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                            <li>{{error}}</li>
                            {% endfor %}
                            {% endfor %}
                </div>
                
            </div>
        </section>
    </center>

{% endblock %}